AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template for S3 bucket that will store the model files.'
Parameters:
  BucketName:
    Description: Bucket for storing model files.
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: 
        Ref: BucketName