apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: localdisk
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: models-pv
spec:
  storageClassName: localdisk
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 30Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /var/sd-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
spec:
  storageClassName: localdisk
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 26Gi

